version: '3.8'

services:
  mongo:
    container_name: gdash_mongo
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: docker
      MONGO_INITDB_DATABASE: gdash_api
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - ./data:/data/db
  mongo-init-replica:
    image: mongo:7
    depends_on:
      - mongo
    entrypoint: >
      bash -c "
        sleep 5 &&
        mongosh --host mongo:27017 --eval '
          rs.initiate({
            _id: \"rs0\",
            members: [{ _id: 0, host: \"mongo:27017\" }]
          })
        '
      "